CM-20507 Cycode CLI - Support commit range + `--monitor` flag
cycodehq-public/cycode-cli pull request #73
Opened 2023-03-02 14:02 UTC by morsa4406

2023-03-06 14:03 UTC, MichalBor requested changes

2023-03-06 14:03 UTC, MichalBor commented on cli/code_scanner.py
> +              required=False)
move to code scan

2023-03-06 14:03 UTC, MichalBor commented on cli/code_scanner.py
> +    scan_parameters = get_scan_parameters(path, monitor)
pass context

2023-03-06 17:00 UTC, morsa4406 commented on cli/code_scanner.py
> +              required=False)
fixed

2023-03-07 08:12 UTC, MichalBor approved these changes

2023-03-07 08:29 UTC, merged